UniversityManagementSystemWebApp/Controllers/CourseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class CourseController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        private CourseManager courseManager = new CourseManager();
        
        public ActionResult Save()
        {
           
            List<SelectListItem> aDepartments = departmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;


            List<SelectListItem> aSemesters = departmentManager.GetAllSemester();
            ViewBag.semesters = aSemesters;


            return View();
        }

        [HttpPost]
        public ActionResult Save(Course aCourse)
        {
            
            List<SelectListItem> aDepartments = departmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;

            List<SelectListItem> aSemesters = departmentManager.GetAllSemester();
            ViewBag.semesters = aSemesters;

            ViewBag.message = courseManager.SaveCourse(aCourse);

            ViewBag.code = aCourse.Code;
            ViewBag.name = aCourse.Name;


            if (ViewBag.message == "Saved")
            {
                ModelState.Clear();    
            }

            return View();
        }




        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            List<Course> courses = courseManager.GetAllCourses();
            List<Course> courseList = courses.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetCourseInfoByCourseId(int courseId)
        {
            List<Course> courses = courseManager.GetAllCourses();
            List<Course> courseList = courses.Where(a => a.Id == courseId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);

        }

        public ActionResult CourseDetails()
        {
            List<Department> departments = departmentManager.GetAllDepartmentsInfo();
            ViewBag.Departments = departments;
            return View();
        }




        public JsonResult GetCourseStatisticsByDeptId(int departmentId)
        {
            List<CourseStatisticView> courseDetailses = courseManager.GetAllCourseDetailsByDeptId(departmentId);
            return Json(courseDetailses, JsonRequestBehavior.AllowGet);
        }


        public ActionResult UnAssignAllCourse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnAssignAllCourse(int? id)
        {
            ViewBag.message = courseManager.UnAssignAllCourse();
            return View();
        }
    }
}

UniversityManagementSystemWebApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        

        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Department aDepartment)
        {

            ViewBag.message = aDepartmentManager.Save(aDepartment);
            ViewBag.code = aDepartment.Code;
            ViewBag.name = aDepartment.Name;

            if (ViewBag.message == "Saved")
            {
                ModelState.Clear(); 
            }

            return View();
        }

        public ActionResult ShowDepartment()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartmentsInfo();
            ViewBag.departments = aDepartments;
            return View();
        }
    }
}

UniversityManagementSystemWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UniversityManagementSystemWebApp/Controllers/StudentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class StudentController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        StudentManager aStudentManager = new StudentManager();
         CourseManager aCourseManager = new CourseManager();
         CourseEnrollmentManager aCourseEnrollmentManager = new CourseEnrollmentManager();
        // GET: /Student/

        public ActionResult Register()
        {
            List<SelectListItem> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;

            return View();
        }

        [HttpPost]
        public ActionResult Register(Student student)
        {
            List<SelectListItem> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;

            ViewBag.message = aStudentManager.SaveStudent(student);

            ViewBag.RegNo = student.RegNo;
            ViewBag.name = student.Name;
            ViewBag.Email = student.Email;
            ViewBag.ContactNo = student.ContactNo;
            ViewBag.Address = student.Address;
            ViewBag.RegDate = student.RegDate.ToString("dd-MM-yyyy");
            ViewBag.DeptName = student.DeptName;

            if (ViewBag.message == "yes")
            {
                ModelState.Clear(); 
            }
            return View();

        }public ActionResult CourseEnrollment()
        {
            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;
            return View();
        }

        [HttpPost]
        public ActionResult CourseEnrollment(CourseEnrollment courseEnrollment)
        {
            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;
            string message = aCourseEnrollmentManager.SaveCourseEnrollment(courseEnrollment);
            if (message == "yes" || message == "conflict")
            {
                ModelState.Clear();
            }
            ViewBag.message = message;
            return View();
        }


        public JsonResult GetStudentById(int studentId)
        {
            List<Student> students = aStudentManager.GetStudentById(studentId);

            return Json(students, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseThatCanBeTakenByStudentId(int studentId)
        {
            List<Student> students = aStudentManager.GetStudentById(studentId);
            int deptId = students[0].DepartmentId;
            List<Course> courses = aCourseManager.GetAllCourses();
            List<Course> courseList = courses.Where(a => a.DepartmentId == deptId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseThatAreTakenByStudentId(int studentId)
        {

            List<Course> courses = aCourseEnrollmentManager.GetAllCoursesTakenByStudentId(studentId);
            //List<Course> courseList = courses.Where(a => a.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveResult()
        {
            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;

            List<SelectListItem> grades = aCourseEnrollmentManager.GetAllGradesSelectListItem();
            ViewBag.Grades = grades;

            return View();
        }

        [HttpPost]
        public ActionResult SaveResult(CourseEnrollment courseEnrollment)
        {
            string msg = aCourseEnrollmentManager.SaveCourseResult(courseEnrollment);
            ViewBag.message = msg;

            if (msg == "yes")
            {
                ModelState.Clear();
            }

            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;

            List<SelectListItem> grades = aCourseEnrollmentManager.GetAllGradesSelectListItem();
            ViewBag.Grades = grades;

            return View();
        }

        public ActionResult ViewResult()
        {
            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;
            return View();
        }

        [HttpPost]
        public ActionResult ViewResult(int studentId)
        {

           
            List<SelectListItem> studentListItem = aStudentManager.GetAllStudentsSelectListItem();
            ViewBag.Students = studentListItem;
            return View();
        }

        public JsonResult GetCourseResultByStudentId(int studentId)
        {

            List<StudentCourseView> results = aCourseEnrollmentManager.GetCourseResultByStudentId(studentId);
            return Json(results, JsonRequestBehavior.AllowGet);
        }


       
    }
}

UniversityManagementSystemWebApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        DepartmentManager aDepartmentManager = new DepartmentManager();
        //
        // GET: /Teacher/
        public ActionResult Save()
        {
            List<SelectListItem> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;

            List<SelectListItem> designations = aTeacherManager.GetAllDesignation();
            ViewBag.designations = designations;



            return View();
        }


        [HttpPost]
        public ActionResult Save(Teacher aTeacher)
        {
            List<SelectListItem> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.departments = aDepartments;

            List<SelectListItem> designations = aTeacherManager.GetAllDesignation();
            ViewBag.designations = designations;

            ViewBag.message = aTeacherManager.SaveTeacher(aTeacher);
            ViewBag.teacherName = aTeacher.Name;
            ViewBag.email = aTeacher.Email;


            if (ViewBag.message == "yes")
            {
                ModelState.Clear(); //clear after submiting
            }
            return View();
        }
        public ActionResult Assign()
        {
            List<Department> departments = aDepartmentManager.GetAllDepartmentsInfo();
            ViewBag.Departments = departments;
            return View();
        }

        [HttpPost]
        public ActionResult Assign(AssignCourse assignCourse)
        {
            string msg = aTeacherManager.AssignCourseToTeacher(assignCourse);
                ModelState.Clear(); 
            ViewBag.Message = msg;
            List<Department> departments = aDepartmentManager.GetAllDepartmentsInfo();
            
            ViewBag.Departments = departments;
            return View();
        }

        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {
            List<Teacher> teachers = aTeacherManager.GetAllTeachers();
            List<Teacher> teacherList = teachers.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }
          
        public JsonResult GetCreditLimitByTeacherId(int teacherId)
        {
            List<Teacher> teachers = aTeacherManager.GetAllTeachers();
            List<Teacher> teacherList = teachers.Where(a => a.Id == teacherId).ToList();
            //double CreditLimit = aTeacher.CreditLimit;
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }
	}
}
        
        
       
    

UniversityManagementSystemWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UniversityManagementSystemWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>IIUC Students Panel - SWP Log In</title>
    <link rel="shortcut icon" href="template/images/favicon.png" type="image/x-icon" />
    <link rel="icon" href="template/images/favicon.png" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" media="all" href="template/style.css" />
    <link rel="stylesheet" type="text/css" media="all" href="template/style_uwp.css" />
</head>
<body class="home blog livecss">
    <div id="header-panel">
        <div class="page">
            <div id="header">
                <div class="header-top">
                    <div class="language">
                        <ul class="lang-list"></ul><!--lang-list end-->
                    </div><!--language end-->
                    <div class="loginrss">
                        <ul class="logrss-list">
                            <li><a href="http://www.iiuc.ac.bd/">IIUC Home</a></li>
                        </ul>
                    </div><!--loginrss end-->
                    <div class="clear"></div>
                </div><!--header-top end-->
                <div class="clear"></div>
                <div class="header-main">
                    <a class="logo" href="#"></a>
                    <div id="ms-bg">
                        <div id="main-menu">
                            <div class="menu-header">

                                <ul><li id="menu-item-615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-615"><a href='' class="sf-with-ul">Log In</a></li></ul>
                            </div>
                        </div><!--main-menu end-->
                        <div id="search">
                        </div><!--search end-->
                        <div class="clear"></div>
                    </div><!--ms-bg end-->
                </div><!--header-main end-->
            </div><!--header end-->
        </div><!--page end-->
    </div><!--header-panel-->
    <div class="page">
        <div class="clear"></div>
        <div id="Content-fullwidth">
            <div id="uwp-cleMain">
                <div id="uwp-user"></div>
                <div id="uwp-filter-info">
                    <table class="uwp-content" cellpadding="2" cellspacing="2" style="border-collapse: collapse; border-width: 0" width="100%">
                        <tr><td style="text-align: center;"><h3>Welcome to IIUC Student Web Panel (SWP)</h3></td></tr>
                    </table>
                </div>
                <div id="rest">
                    <div class="uwp-prop"></div>
                    <div id="msgBar"></div>
                    <div id="cleContent">
                        <form method="POST" action="/index.php">
                            <table class="login" cellpadding="2" cellspacing="2" style="border-collapse: collapse" align="center" width="300" height="200">
                                <tr>
                                    <td width="100%" colspan="3">
                                        <p align="center">
                                    </td>
                                </tr>
                                <tr>
                                    <td width="100%" colspan="3"><center><font size=2 face=tahoma><marquee behavior=alternate><p><b><p><b>Please enter your Log-in Information.</b><p><p><b></b></b></marquee></font></center></td>
                                </tr>
                                <tr>
                                    <td width="24%"><b><font face="Arial">Student-ID</font></b></td>
                                    <td width="6%"><b><font face="Arial">:</font></b></td>
                                    <td width="70%"><input type="text" name="studentID" size="20" maxlength="9" class=class1 style="text-transform:uppercase;"></td>
                                </tr>
                                <tr>
                                    <td width="24%"><b><font face="Arial">Password</font></b></td>
                                    <td width="6%"><b><font face="Arial">:</font></b></td>
                                    <td width="70%"><input type="password" name="password" size="20" maxlength="20" class=class1></td>
                                </tr>

                                <tr>
                                    <td width="100%" colspan="3">
                                        <!--<center><font size=2 face=tahoma><marquee BEHAVIOR=alternate><p><b>Please enter your Log-in Information.</b><p></marquee></font></center>
                                        <br /> -->
                                        <center><input type="submit" size="30" value="Log-in" class=class1><input type='button' onclick='javascript:window.close();' value='close' class=class1></center>
                                    </td>
                                </tr>

                                <tr>
                                    <td align="center" width="100%" colspan="3" class="uwp-info">
                                        Forgot your password?
                                        <a class="uwp-label" href="forgotPassword.php">Click Here</a>
                                    </td>
                                </tr>
                            </table>
                        </form>

                        <table class="uwp-noborder" cellpadding="2" cellspacing="2" style="border-collapse: collapse; border-width: 0" width="90%">
                            <!--<tr><td><h3> Attention : Student who have finished Registration, Click your profile and see the registartion status:Confirmed or Pending if pending, contact your advisor for confirmation. Also, any ADD/DROP will be conducted by CoE,IIUC as per schedule in the Academic Calendar at <a href="https://www.iiuc.ac.bd/academic/academic-calendar-2/academic-calendar/">Academic Calendar Spring 2016</a></h3></td></tr>
                            <!--<tr><td><h3> Attention : MBA EMBA MBM Registration Schedule for Spring 2016 <a href="notices\spring-16\MBA-MBM-Reg-Schedule-Spring16.pdf"> Read the Notice for MBA EMBA MBM (Spring 2016)</a></h3></td></tr>
                            <tr><td><h3> Attention : Undergraduate Registration Schedule for Spring 2016 <a href="Reg-schedule-1st-sem-Spring16.pdf"> Read the Notice undergraduate programs</a></h3></td></tr>
                            <tr><td><h3> Attention : Strudent's of MBA EMBA MBM <a href="notices\spring-16\notice for mba & mbm.pdf"> Read the Notice Payment Clearance on Friday</a></h3></td></tr>
                            <tr><td><h3> Attention : First Semester Collect your Password from Dept. Office. Rest of you <a href="password-retrieve-how-to.pdf"> Read Password-How-To</a></h3></td></tr>
                            <tr><td align="center"><h3> Attention :<a href="#" target="_blank"> 1st Semester Registration running now. <br/>2nd Semester to on-ward registration for current semster will be open soon<br/>Registration URL(Admitted Current Semester): https://iiuc.ac.bd/login</a></h3></td></tr>-->
                        </table>


                    </div>
                </div>
            </div><div class="clear"></div>
        </div>
        <!--content end-->
        <div id="footer">
            <div class="box986-top">
                <div class="box986-bottom">
                    <div class="box986-mid">
                        <div class="footer-widget-section">
                            <div class="clear"></div>
                        </div><!--footer-widget end-->
                    </div><!--box-487-mid end-->
                    <div class="copyright-social">
                        <div class="copyright">
                            <p>
                                Copyright © 2016
                                <a href="./International Islamic University Chittagong_files/International Islamic University Chittagong.htm">IIUC</a>
                                | All Rights Reserved
                            </p>
                        </div><!--copyright end-->
                        <div class="counter">
                            <div class="footer-widget-5">
                                <div class="textwidget">
                                </div>
                            </div>
                        </div>
                        <div class="social">
                            <p>
                                System developed by:
                                <a href="http://www.vpcsbd.com">ValuePLUS Computer Systems Ltd.</a>
                            </p>
                        </div><!--social end-->
                        <div class="clear"></div>
                    </div><!--copyright-social end-->
                </div><!--box-487-bottom end-->
            </div><!--box-487-top end-->
        </div><!--footer end-->
        <!--stats_footer_test-->
    </div>
</body>

</html>

UniversityManagementSystemWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/css/style.css" rel="stylesheet"/>
<style>
    .button {
        display: inline-block;
        padding: 25px 25px;
        font-size: 24px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #fff;
        background-color: #312D2D;
        border: none;
        border-radius: 15px;
        box-shadow: 0 9px #999;
    }

        .button:hover {
            background-color: blue;
        }

        .button:active {
            background-color: #CAB7B7;
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }
    table#albums {
        border-collapse: separate;
        border-spacing: 85px 30px;
    }
</style>
    <ul >
        <li><img width="100%" height="300" src="~/images/bitm.png" alt="&quot;Academic building &quot;" /></li>
    </ul>

<div class="jumbotron">

    <marquee bgcolor="#000000" scrollamount="15">
        <h2 style="font-size: 60px; color: yellowgreen">Welcome To BITM University !</h2></marquee>
</div>

    <div align="center">
        <
        <table  id="albums">
            <tr>
                <td>
                    <div >
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("Save", "Department")'">Save Department</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("ShowDepartment", "Department")'">View Department</button>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("Save", "Course")'">Save Course</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("CourseDetails", "Course")'">Course Details</button>
                        </div>
                    </div>
                </td>
               
            </tr>



            <tr>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("Save", "Teacher")'">Save Teacher</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("Assign", "Teacher")'">Teacher Course <br/> Assign</button>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("Register", "Student")'">Register Student</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("CourseEnrollment", "Student")'"> Enroll A Course</button>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("SaveResult", "Student")'">Save Result</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("ViewResult", "Student")'"> View Result</button>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("AllocateClassrooms", " ClassAllocation")'">Allocate Classroom</button>
                        </div>
                    </div>
                </td>
                <td>
                    <div>
                        <div style="width: 300px; height:180px;">
                            <button class="button" type="submit" onclick="window.location = '@Url.Action("CompleteClassSchedule", " ClassAllocation")'"> Class Schedule </button>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    
</div>


<script>
function departmentSaveClick(){
    document.location = 'Department/Save';
}
</script>
    <script src="~/Scripts/image_slide.js"></script>